image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: rEcNnwXVAL90HPlXLc/NMc7yuZDpNfSF/fNIR5MP60CQDbNUye4g2dFStVHV5vH9
install:
- pip install -r requirements.txt
- pip install pyinstaller

build_script:
- pyinstaller -F main.py --add-data icon.png:icon.png -n turno-gusano

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a turno-gusano-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: turno-gusano-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf turno-gusano-macos.tar.gz -C dist turno-gusano

  artifacts:
  - path: turno-gusano-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf turno-gusano-linux.tar.gz -C dist turno-gusano

  artifacts:
  - path: Names.rand-linux.tar.gz

